### ISSUE TITLE
我想增加产品，求后台管理系统地址，localhost:7777/admin/list不行

### ISSUE THREAD

**Issue by lvjw1991** [Richar-Dada/cakeShop#3]
![image](https://user-images.githubusercontent.com/29093438/231254711-3c372ce0-f071-426b-818b-af56f68421fe.png)

**Comment by zhangheng950229** [comment]
什么技术栈啊？vue  还是JQuer 还是react?
如果是vue 或者是react  看下router 配置的对不对

**Comment by zhangheng950229** [comment]
求后台管理系统地址，localhost:7777/admin/list不行
你这个问题是什么意思？想表达什么？
是获取不到数据？还是该地址访问不了网页？

**Comment by lvjw1991** [comment]
> 求后台管理系统地址，localhost:7777/admin/list不行 你这个问题是什么意思？想表达什么？ 是获取不到数据？还是该地址访问不了网页？

我不知道是哪个地址，这个地址不行如上图

**Comment by lvjw1991** [comment]
代码有问题，真坑
![image](https://user-images.githubusercontent.com/29093438/231849149-73823d6d-2dba-44f1-8826-25f3f586dae5.png)
![image](https://user-images.githubusercontent.com/29093438/231849505-63f28f8d-3ba7-41aa-b612-fd55426f9e80.png)
